# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d1896cf887856d01a58cefc1028d1f80f900059e913ce345b62a4833fd848977458594a060c7bd080e9c098608d77c7b4fd57f5a1995c9ab6f98d0fe35e61c8

test:
  secret_key_base: 5982850ee5be91026fc0bc0b007207d5f4116d17cf5d103c1d8574fe1e74691e4086d7f2a05d9f8dc441ee836145cf007d6f6e29f09553aab8ad3d6b862bc801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
